@url = http://127.0.0.1:42069/api

### create_note
POST {{url}}/notes
content-type: application/json

{
    "title": "wah",
    "body": "Ninomae Ina'nis is Cute"
}

### read_notes
GET {{url}}/notes

### update_note
PUT {{url}}/notes/1
content-type: application/json

{
    "title": "wah",
    "body": "Ninomae Ina'nis is Super Cute"
}

### delete_note
DELETE  {{url}}/notes/1