@url = http://127.0.0.1:42069/api

###

# @name login
POST {{url}}/users/login
Content-Type: application/json

{
    "username": "kyaruwo",
    "password": "ninomae_ina'nis"
}

###

# @name write_note
POST {{url}}/notes
Content-Type: application/json
Cookie: session_id={{login.response.body.$.session_id}};

{
    "title": "wah",
    "body": "Ninomae Ina'nis is Cute"
}

### read_notes
GET {{url}}/notes
Cookie: session_id={{login.response.body.$.session_id}};

### read_note
GET {{url}}/notes/{{write_note.response.body.$.note_id}}
Cookie: session_id={{login.response.body.$.session_id}};

### update_note
PUT {{url}}/notes/{{write_note.response.body.$.note_id}}
Content-Type: application/json
Cookie: session_id={{login.response.body.$.session_id}};

{
    "title": "wah",
    "body": "Ninomae Ina'nis is Super Cute"
}

### delete_note
DELETE {{url}}/notes/{{write_note.response.body.$.note_id}}
Cookie: session_id={{login.response.body.$.session_id}};
