@url = http://127.0.0.1:42069/api

@token = token

### create_note
POST {{url}}/notes
Authorization: Bearer {{token}}
content-type: application/json

{
    "title": "wah",
    "body": "Ninomae Ina'nis is Cute"
}

### read_note
GET {{url}}/notes/1
Authorization: Bearer {{token}}

### read_notes
GET {{url}}/notes
Authorization: Bearer {{token}}

### update_note
PUT {{url}}/notes/1
Authorization: Bearer {{token}}
content-type: application/json

{
    "title": "wah",
    "body": "Ninomae Ina'nis is Super Cute"
}

### delete_note
DELETE  {{url}}/notes/1
Authorization: Bearer {{token}}