@url = http://127.0.0.1:42069/api/users

### register
POST {{url}}/register
Content-Type: application/json

{
    "email": "{{email}}",
    "username": "kyaruwo",
    "password": "ninomae_ina'nis"
}

### code_request
POST {{url}}/code_request
Content-Type: application/json

{
    "email": "{{email}}"
}

### verify_email
PUT {{url}}/verify_email
Content-Type: application/json

{
    "email": "{{email}}",
    "code": 88888888
}

###

# @name login
POST {{url}}/login
Content-Type: application/json

{
    "username": "kyaruwo",
    "password": "ninomae_ina'nis"
}

### logout
PUT {{url}}/logout
Cookie: session_id={{login.response.body.$.session_id}};

### change_email_request
POST {{url}}/change_email_request
Content-Type: application/json
Cookie: session_id={{login.response.body.$.session_id}};

{
    "email": "{{email}}"
}

### new_email
PUT {{url}}/new_email
Content-Type: application/json
Cookie: session_id={{login.response.body.$.session_id}};

{
    "old_email": "{{email}}",
    "new_email": "{{email}}",
    "code": 88888888
}

### username
PUT {{url}}/username
Content-Type: application/json
Cookie: session_id={{login.response.body.$.session_id}};

{
    "username": "kyaruwo"
}

### password
PUT {{url}}/password
Content-Type: application/json
Cookie: session_id={{login.response.body.$.session_id}};

{
    "old_password": "ninomae_ina'nis",
    "new_password": "ninomae_ina'nis_cute"
}