@url = http://127.0.0.1:42069/api

@email = testmail@gmail.com

### register
POST {{url}}/users/register
content-type: application/json

{
    "email": "{{email}}",
    "name": "kyaruwo",
    "password": "ninomae_ina'nis"
}

### request_code
POST {{url}}/users/request_code
content-type: application/json

{
    "email": "{{email}}"
}

###

# @name login
POST {{url}}/users/login
content-type: application/json

{
    "name": "kyaruwo",
    "password": "ninomae_ina'nis"
}

### token
PUT {{url}}/users/token
Cookie: token={{login.response.body.$.token}};