[package]
name = "sumire"
version = "0.1.0"
edition = "2021"
authors = ["kyaruwo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# core
tokio = { version = "1.34.0", features = ["full"] }
axum = "0.7.1"
sqlx = { version = "0.7.3", features = [
    "mysql",
    "runtime-tokio",
    "tls-rustls",
] }

# json
serde = { version = "1.0.193", features = ["derive"] }
validator = { version = "0.16.1", features = ["derive"] }

# regex
lazy_static = "1.4.0"
regex = "1.10.2"

# password
argon2 = "0.5.2"

# util
dotenvy = "0.15.7"
rand = "0.8.5"
