[package]
name = "sumire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
axum = "0.6.20"
serde = { version = "1.0.192", features = ["derive"] }
validator = { version = "0.16.1", features = ["derive"] }
sqlx = { version = "0.7.2", features = [
    "mysql",
    "runtime-tokio",
    "tls-rustls",
] }
