DROP DATABASE IF EXISTS sumire;

CREATE DATABASE sumire;

use sumire;

CREATE TABLE Users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARBINARY(32) UNIQUE NOT NULL,
    `password` BLOB NOT NULL,
    `token` VARBINARY(432) UNIQUE
);

CREATE TABLE UsersLogs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `request` TEXT NOT NULL,
    `response` TEXT NOT NULL,
    `datetime` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Notes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `title` VARBINARY(54) NOT NULL,
    `body` VARBINARY(432) NOT NULL
);

CREATE TABLE NotesLogs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `request` TEXT NOT NULL,
    `note_id` BIGINT NOT NULL,
    `response` TEXT NOT NULL,
    `datetime` DATETIME DEFAULT CURRENT_TIMESTAMP
);