DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY,
    SESSION_ID TEXT UNIQUE,
    EMAIL TEXT UNIQUE NOT NULL,
    USERNAME TEXT UNIQUE NOT NULL,
    PASSWORD_HASH TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

DROP TABLE IF EXISTS NOTES;

CREATE TABLE NOTES (
    NOTE_ID UUID PRIMARY KEY,
    USER_ID UUID,
    TITLE TEXT,
    BODY TEXT,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);